export const SOFTWARE_PROJECTS_SEED = [
  {
    id: 1,
    name: 'Acerola Ticket',
    description: 'Sistema central de chamados, suporte interno e governança de TI.',
    repositoryUrl: 'vinicius-gpl/acerola-ticket',
    githubRepoOwner: 'vinicius-gpl',
    githubRepoName: 'acerola-ticket',
    status: 'active' as const,
    color: 'blue' as const,
    createdBy: 'seed@empresa.com.br',
    createdAt: new Date('2026-01-10T08:00:00.000Z'),
    updatedAt: new Date('2026-03-01T10:00:00.000Z'),
  },
  {
    id: 2,
    name: 'Portal do Cliente',
    description: 'Interface web para clientes acompanharem pedidos e emitirem 2ª via de faturas.',
    repositoryUrl: 'vinicius-gpl/portal-cliente',
    githubRepoOwner: 'vinicius-gpl',
    githubRepoName: 'portal-cliente',
    status: 'active' as const,
    color: 'green' as const,
    createdBy: 'seed@empresa.com.br',
    createdAt: new Date('2026-01-15T09:00:00.000Z'),
    updatedAt: new Date('2026-03-05T14:30:00.000Z'),
  },
  {
    id: 3,
    name: 'App Mobile Operacional',
    description: 'Aplicativo dos motoristas e técnicos de campo com sincronização offline.',
    repositoryUrl: 'vinicius-gpl/mobile-app',
    githubRepoOwner: 'vinicius-gpl',
    githubRepoName: 'mobile-app',
    status: 'maintenance' as const,
    color: 'purple' as const,
    createdBy: 'seed@empresa.com.br',
    createdAt: new Date('2025-11-20T10:00:00.000Z'),
    updatedAt: new Date('2026-02-28T16:00:00.000Z'),
  },
  {
    id: 4,
    name: 'ERP Financeiro Legado',
    description: 'Módulo fiscal e de faturamento em processo de migração para o novo ERP.',
    repositoryUrl: 'vinicius-gpl/erp-legacy',
    githubRepoOwner: 'vinicius-gpl',
    githubRepoName: 'erp-legacy',
    status: 'deprecated' as const,
    color: 'amber' as const,
    createdBy: 'seed@empresa.com.br',
    createdAt: new Date('2024-05-10T08:00:00.000Z'),
    updatedAt: new Date('2026-01-15T11:00:00.000Z'),
  },
];

export const SOFTWARE_TIMELINE_SEED = [
  {
    id: 1,
    projectId: 1,
    type: 'pr' as const,
    externalId: '#104',
    title: 'feat: Integração com GitHub Issues e Timeline',
    description: 'Criação de issues em background e sincronização de PRs.',
    url: 'https://github.com/vinicius-gpl/acerola-ticket/pull/104',
    author: 'vinicius-gpl',
    status: 'merged' as const,
    createdBy: 'seed@empresa.com.br',
    eventDate: new Date('2026-10-06T15:30:00.000Z'),
    createdAt: new Date('2026-10-06T15:30:00.000Z'),
  },
  {
    id: 2,
    projectId: 1,
    type: 'pr' as const,
    externalId: '#103',
    title: 'feat: Grade de cronograma semanal e alocação de sprints',
    description: 'Visualização semanal estilo time grid com indicadores de hora atual.',
    url: 'https://github.com/vinicius-gpl/acerola-ticket/pull/103',
    author: 'vinicius-gpl',
    status: 'merged' as const,
    createdBy: 'seed@empresa.com.br',
    eventDate: new Date('2026-10-05T18:00:00.000Z'),
    createdAt: new Date('2026-10-05T18:00:00.000Z'),
  },
  {
    id: 3,
    projectId: 1,
    type: 'pr' as const,
    externalId: '#102',
    title: 'feat: Visualização em Kanban dos chamados de Sistema',
    description: 'Quadro interativo com estágios do suporte.',
    url: 'https://github.com/vinicius-gpl/acerola-ticket/pull/102',
    author: 'vinicius-gpl',
    status: 'merged' as const,
    createdBy: 'seed@empresa.com.br',
    eventDate: new Date('2026-10-04T11:20:00.000Z'),
    createdAt: new Date('2026-10-04T11:20:00.000Z'),
  },
  {
    id: 4,
    projectId: 2,
    type: 'pr' as const,
    externalId: '#42',
    title: 'fix: Otimização de consultas no extrato financeiro',
    description: 'Adicionados índices parciais no banco Postgres.',
    url: 'https://github.com/vinicius-gpl/portal-cliente/pull/42',
    author: 'dev-team',
    status: 'merged' as const,
    createdBy: 'seed@empresa.com.br',
    eventDate: new Date('2026-10-03T09:45:00.000Z'),
    createdAt: new Date('2026-10-03T09:45:00.000Z'),
  },
  {
    id: 5,
    projectId: 2,
    type: 'issue' as const,
    externalId: 'CH-0045',
    title: 'Chamado vinculado: Lentidão ao emitir boleto',
    description: 'Relatado pelo financeiro e resolvido na release v1.4.',
    url: null,
    author: 'Equipe de Suporte',
    status: 'closed' as const,
    createdBy: 'seed@empresa.com.br',
    eventDate: new Date('2026-10-02T14:10:00.000Z'),
    createdAt: new Date('2026-10-02T14:10:00.000Z'),
  },
];

export function getScheduleSeed() {
  const now = new Date();
  const dayOfWeek = now.getDay();
  const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
  const monday = new Date(now);
  monday.setDate(now.getDate() + mondayOffset);

  function offsetDateStr(days: number): string {
    const d = new Date(monday);
    d.setDate(monday.getDate() + days);
    return d.toISOString().slice(0, 10);
  }

  return [
    {
      id: 1,
      title: 'Deploy da v1.4 e testes de carga',
      note: 'Publicação no ambiente de produção do Portal do Cliente.',
      projectId: 2,
      date: offsetDateStr(0),
      startTime: '09:00',
      endTime: '11:00',
      color: 'green' as const,
      category: 'deploy' as const,
      createdBy: 'seed@empresa.com.br',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 2,
      title: 'Sprint Planning e Refinamento de Backlog',
      note: 'Definição das tarefas prioritárias de desenvolvimento.',
      projectId: 1,
      date: offsetDateStr(1),
      startTime: '10:00',
      endTime: '12:00',
      color: 'blue' as const,
      category: 'standup' as const,
      createdBy: 'seed@empresa.com.br',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 3,
      title: 'Refatoração da API e Correção de Bugs',
      note: 'Otimização dos endpoints do Acerola Ticket.',
      projectId: 1,
      date: offsetDateStr(2),
      startTime: '14:00',
      endTime: '16:30',
      color: 'purple' as const,
      category: 'review' as const,
      createdBy: 'seed@empresa.com.br',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 4,
      title: 'Manutenção Preventiva de Banco de Dados',
      note: 'Vacuum e reindex nas tabelas do ERP.',
      projectId: 4,
      date: offsetDateStr(3),
      startTime: '08:30',
      endTime: '10:00',
      color: 'amber' as const,
      category: 'maintenance' as const,
      createdBy: 'seed@empresa.com.br',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 5,
      title: 'Review e Demonstração da Sprint',
      note: 'Apresentação das novidades para as lideranças.',
      projectId: null,
      date: offsetDateStr(4),
      startTime: '15:00',
      endTime: '17:00',
      color: 'neutral' as const,
      category: 'review' as const,
      createdBy: 'seed@empresa.com.br',
      createdAt: now,
      updatedAt: now,
    },
  ];
}
