import { type TicketInsert } from '../../../server/src/lib/db/schema/tickets.schema';

/**
 * Os dados de teste de chamados. VERSIONADOS: toda máquina que rodar o seed vê exatamente isto.
 *
 * O `id` é fixo de propósito — é a chave que torna o seed idempotente, e é também o protocolo
 * que aparece na tela (`CH-0001`).
 *
 * Dado INVENTADO, sempre. Nome de colega, telefone de verdade, print de tela real: nada disso
 * entra aqui, porque este arquivo vai para o git e fica no histórico para sempre. Os telefones
 * usam o prefixo 99999, que não existe como número atribuído.
 */
const ATTENDANT = 'suporte@azuos.local';

/* Datas fixas: um seed com `new Date()` mudaria o tempo médio de resolução a cada execução,
   e o indicador do painel nunca poderia ser conferido de uma rodada para a outra. */
const at = (value: string) => new Date(value);

export const TICKETS_SEED: TicketInsert[] = [
  {
    id: 1,
    status: 'resolved',
    priority: 'high',
    requesterName: 'Bia Costa',
    department: 'financeiro',
    problemType: 'printer',
    anydeskId: '111 222 333',
    contactPhone: '62999990001',
    notifyWhatsapp: true,
    description: 'A impressora da sala não puxa papel e trava no meio da folha.',
    assignee: 'Suporte TI',
    solution: 'Retirei uma folha presa no rolete e limpei o tracionador.',
    createdAt: at('2026-09-15T12:10:00.000Z'),
    startedAt: at('2026-09-15T12:40:00.000Z'),
    resolvedAt: at('2026-09-15T14:10:00.000Z'),
    updatedAt: at('2026-09-15T14:10:00.000Z'),
    updatedBy: ATTENDANT,
  },
  {
    id: 2,
    status: 'open',
    priority: 'high',
    requesterName: 'Carlos Menezes',
    department: 'rh',
    problemType: 'network',
    anydeskId: null,
    contactPhone: '62999990002',
    notifyWhatsapp: true,
    description: 'A internet cai de cinco em cinco minutos desde ontem à tarde.',
    createdAt: at('2026-09-21T11:30:00.000Z'),
  },
  {
    id: 3,
    status: 'in_progress',
    priority: 'medium',
    requesterName: 'Daniela Prado',
    department: 'comercial',
    problemType: 'slow_computer',
    anydeskId: '444 555 666',
    contactPhone: '62999990003',
    notifyWhatsapp: false,
    description: 'O computador demora uns dez minutos para abrir qualquer programa.',
    assignee: 'Suporte TI',
    createdAt: at('2026-09-20T13:05:00.000Z'),
    startedAt: at('2026-09-21T12:00:00.000Z'),
    updatedAt: at('2026-09-21T12:00:00.000Z'),
    updatedBy: ATTENDANT,
  },
  {
    id: 4,
    /* Caso limite: chamado aberto por engano. Ele não some — vira cancelado, e continua no
       histórico sem entrar na média de resolução. */
    status: 'cancelled',
    priority: 'low',
    requesterName: 'Eduardo Lima',
    department: 'cs',
    problemType: 'other',
    anydeskId: null,
    contactPhone: '62999990004',
    notifyWhatsapp: false,
    description: 'Abri sem querer, pode desconsiderar.',
    assignee: 'Suporte TI',
    solution: 'Duplicado do CH-0002.',
    createdAt: at('2026-09-21T13:00:00.000Z'),
    updatedAt: at('2026-09-21T13:20:00.000Z'),
    updatedBy: ATTENDANT,
  },
  {
    id: 5,
    status: 'open',
    priority: 'medium',
    requesterName: 'Fernanda Rocha',
    department: 'fiscal',
    problemType: 'email',
    anydeskId: null,
    contactPhone: '62999990005',
    notifyWhatsapp: true,
    description: 'Não consigo enviar e-mail com anexo maior que 2 MB, dá erro de envio.',
    createdAt: at('2026-09-22T11:15:00.000Z'),
  },
  {
    id: 6,
    status: 'resolved',
    priority: 'high',
    requesterName: 'Gustavo Aires',
    department: 'contabil',
    problemType: 'digital_certificate',
    anydeskId: '777 888 999',
    contactPhone: '62999990006',
    notifyWhatsapp: false,
    description: 'O certificado digital não é reconhecido ao assinar no portal.',
    assignee: 'Suporte TI',
    solution: 'Reinstalei o driver do token e atualizei a cadeia de certificados.',
    createdAt: at('2026-09-16T11:00:00.000Z'),
    startedAt: at('2026-09-16T11:20:00.000Z'),
    resolvedAt: at('2026-09-16T12:50:00.000Z'),
    updatedAt: at('2026-09-16T12:50:00.000Z'),
    updatedBy: ATTENDANT,
  },
  {
    id: 7,
    status: 'open',
    priority: 'low',
    requesterName: 'Helena Dias',
    department: 'recepcao',
    problemType: 'remote_access',
    anydeskId: '123 456 789',
    contactPhone: '62999990007',
    notifyWhatsapp: false,
    description: 'Preciso do AnyDesk instalado no computador novo da recepção.',
    createdAt: at('2026-09-22T12:40:00.000Z'),
  },
  {
    id: 8,
    status: 'in_progress',
    priority: 'high',
    requesterName: 'Igor Fontes',
    department: 'paralegal',
    problemType: 'internal_system',
    anydeskId: null,
    contactPhone: '62999990008',
    notifyWhatsapp: true,
    description: 'O sistema interno desloga sozinho toda vez que eu salvo um processo.',
    assignee: 'Suporte TI',
    createdAt: at('2026-09-19T14:00:00.000Z'),
    startedAt: at('2026-09-22T11:00:00.000Z'),
    updatedAt: at('2026-09-22T11:00:00.000Z'),
    updatedBy: ATTENDANT,
  },
  {
    id: 9,
    /* Caso limite: descrição longa, para a lista ter que truncar sem quebrar o desenho. */
    status: 'open',
    priority: 'medium',
    requesterName: 'Joana Vilela',
    department: 'pessoal',
    problemType: 'other',
    anydeskId: null,
    contactPhone: '62999990009',
    notifyWhatsapp: false,
    description:
      'Bom dia. Desde a atualização de ontem o computador liga, mostra a tela de boas-vindas, ' +
      'fica alguns minutos carregando e só então abre a área de trabalho. Quando abre, os ícones ' +
      'demoram para aparecer e o antivírus reclama de um arquivo que não consigo ler o nome. ' +
      'Tentei reiniciar três vezes e desligar da tomada, mas continua igual. O mouse também ' +
      'trava por uns segundos de vez em quando, principalmente quando abro a planilha grande ' +
      'do fechamento. Não sei se é o mesmo problema ou se são dois.',
    createdAt: at('2026-09-22T10:20:00.000Z'),
  },
  {
    id: 10,
    status: 'resolved',
    priority: 'low',
    requesterName: 'Kleber Antunes',
    department: 'analyze',
    problemType: 'software_install',
    anydeskId: null,
    contactPhone: '62999990010',
    notifyWhatsapp: false,
    description: 'Preciso do leitor de PDF instalado para abrir os laudos.',
    assignee: 'Suporte TI',
    solution: 'Instalado e configurado como leitor padrão.',
    createdAt: at('2026-09-18T12:00:00.000Z'),
    startedAt: at('2026-09-18T12:30:00.000Z'),
    resolvedAt: at('2026-09-18T12:45:00.000Z'),
    updatedAt: at('2026-09-18T12:45:00.000Z'),
    updatedBy: ATTENDANT,
  },
  {
    id: 11,
    /* Caso limite: sem AnyDesk e sem aviso no WhatsApp — o mínimo que o formulário aceita. */
    status: 'open',
    priority: 'medium',
    requesterName: 'Lúcia Barreto',
    department: 'certificado',
    problemType: 'printer',
    anydeskId: null,
    contactPhone: '62999990011',
    notifyWhatsapp: false,
    description: 'A impressora está imprimindo tudo borrado.',
    createdAt: at('2026-09-22T09:05:00.000Z'),
  },
  {
    id: 12,
    /* Caso limite: resolvido em quinze minutos — o piso do tempo médio. */
    status: 'resolved',
    priority: 'medium',
    requesterName: 'Marcos Tavares',
    department: 'comercial',
    problemType: 'network',
    anydeskId: null,
    contactPhone: '62999990012',
    notifyWhatsapp: true,
    description: 'O cabo de rede da minha mesa não dá sinal.',
    assignee: 'Suporte TI',
    solution: 'Troquei o cabo e reorganizei a porta no switch.',
    createdAt: at('2026-09-17T13:00:00.000Z'),
    startedAt: at('2026-09-17T13:05:00.000Z'),
    resolvedAt: at('2026-09-17T13:15:00.000Z'),
    updatedAt: at('2026-09-17T13:15:00.000Z'),
    updatedBy: ATTENDANT,
  },
];
